### ISSUE TITLE
Questions / Concerns

### ISSUE THREAD

**Issue by mxms0** [nibanks/quic-disable-encryption#1]
Should peers communicating over plaintext channel support multipath / migration? This may be unintentional in the general case and lead to data leakage. 

I understand this is intended to be used over a trusted channel. One of the main usages I see for this is file transfer. Establish secure connection, negotiate file transfers, then move to plaintext for the actual transfer, and then re-encrypt later on. 

So then, is it possible for peers to re-negotiate encryption? If so, what would this look like? My big worry in re-enabling encryption is that a malicious third-party could jump in and re-enable encryption with their own specified parameters (i.e. session hijack). So I suppose what would have to happen if we wanted to re-encrypt the channel, is that we would only be able to use pre-shared key material during the initial encryption phase, and never re-negotiate that info in the open. (Probably obvious to you)

**Comment by nibanks** [comment]
As this isn't meant to be used on the open internet, I don't think migration is actually very relevant. This is only used if the path is completely trusted. If you want to change to an untrusted path, then you should just create a new connection. I don't think it is worth the complexity to try to support re-enabling encryption or making the decision/negotiation per-path. This is just a simple, big on/off button.

**Comment by mxms0** [comment]
Agreed; So what is the expected behavior if someones tries to migrate, likely unintentionally?

**Comment by nibanks** [comment]
If both sides chose to disable encryption, then they should completely trust the path between them; including all middleboxes. If anything can cause a migration (e.g. NAT rebinding) then that must be taken into account when evaluation the "trust" of the network. Bottom line, don't disable encryption if your traffic might go into/through an untrusted domain.

**Comment by nibanks** [comment]
Let me know if you think any actual text should be added to the draft for this. Closing for now though.
